# Generated by Django 5.2.13 on 2026-04-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Menu',
            new_name='MenuModel',
        ),
    ]
